name       : krdc
version    : 19.08.2
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/krdc-19.08.2.tar.xz : c5e6193115afe742f25365bacb55aea21428acf38407659f77636217c589d8ff
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : network.util
summary    : KDE's remote desktop client
description: |
    KRDC is a client application that allows you to view or even control the desktop session on another machine that is running a compatible server. VNC and RDP are supported.
builddeps  :
    - pkgconfig(freerdp2)
    - pkgconfig(libvncserver)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kbookmarks-devel
    - kcmutils-devel
    - kcompletion-devel
    - kdnssd-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kwallet-devel
    - kwindowsystem-devel
    - kxmlgui-devel
rundeps    :
    - freerdp
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
