name       : krdc
version    : 19.08.3
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/krdc-19.08.3.tar.xz : d4cbaebaa3cd56ef5ec728a1d09edf72e8dfc18174e59f954a5f7ec8494acfdc
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : network.util
summary    : KDE's remote desktop client
description: |
    KRDC is a client application that allows you to view or even control the desktop session on another machine that is running a compatible server. VNC and RDP are supported.
builddeps  :
    - pkgconfig(freerdp2)
    - pkgconfig(libvncserver)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kbookmarks-devel
    - kcmutils-devel
    - kcompletion-devel
    - kdnssd-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kwallet-devel
    - kwindowsystem-devel
    - kxmlgui-devel
rundeps    :
    - freerdp
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
